config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Site root.
  root 'home#index'

  # Authentication.
  devise_for :users

  # Clients
  resources :client do
    get '/deactivate', to: 'client#deactivate'
  end

  # Importations.
  scope '/importation' do
    get '/sales', to: 'importation#sales'
    post '/sales', to: 'importation#import_sales_xls'

    get '/payments', to: 'importation#payments'
    post '/payments', to: 'importation#import_payments_xls'
  end

  # Exportations.
  scope '/exportation' do
    get '/charges', to: 'exportation#generate_charges'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord

  def to_s
    self.name
  end

end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :campaign
  has_many :sales

  has_many :payments

  def self.pendign_payments_csv
    attributes = [
      'Nombres', 'Apellidos', 'Cédula',
      'Celular', 'Campana', 'Direccion',
      'Ciudad', 'Fecha de venta',
      'Valor', 'No tarjeta'
    ]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      self.with_pending_charges.each do |client|
        csv << [
          client.first_name,
          client.last_name,
          client.document_number,
          client.cellphone_number,
          client.campaign.name,
          client.address,
          client.city,
          client.sales.first.created_at,
          client.sales.first.amount,
          client.sales.first.card_number,
        ]
      end
    end
  end

  #
  # Return a list of clients that have payments.
  #
  def self.with_pending_charges
    # Clients that that have payments but the last one last date is before today.
    clients_with_active_payments = Payment.where("end_date > ?", Time.zone.now.end_of_day).distinct().pluck('client_id')

    # Clients that have no payments.
    Client.includes(:payments).where(payments: {client_id: nil}) +  Client.where(
      is_active: true,
    ).where.not(
      id: [clients_with_active_payments]
    )
  end


  def self.to_csv(is_active: true)
    attributes = [
      'Nombres', 'Apellidos', 'Cédula',
      'Celular', 'Campana', 'Direccion', 'Ciudad'
    ]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      Client.where(is_active: is_active).each do |client|
        csv << [
          client.first_name,
          client.last_name,
          client.document_number,
          client.cellphone_number,
          client.campaign.name,
          client.address,
          client.city
        ]
      end
    end
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

end

app/models/payment.rb
class Payment < ApplicationRecord

  belongs_to :client
  belongs_to :sale

end

app/models/sale.rb
class Sale < ApplicationRecord

  belongs_to :client
  belongs_to :campaign

  def to_s
    self.card_number
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

end

app/controllers/client_controller.rb
class ClientController < ApplicationController

  #
  # Shows the list of clients in the app
  #
  def index
    @client_list = Client.where(is_active: true)
    is_active = true
    filename = 'clientes-activos'

    if params[:status] == 'inactive'
      is_active = false
      filename = 'clientes-inactivos'
      @client_list = Client.where(is_active: false)
    end

    respond_to do |format|
      format.csv { send_data Client.to_csv(is_active: is_active), filename: "#{filename}.csv" }
      format.html { render :index }
    end
  end

  #
  # Displays the detail page of a client.
  #
  def show
    @client = Client.find(params[:id])
  end

  #
  # Deactivates a client changeing `is_active` to false.
  #
  def deactivate
    @client = Client.find(params[:client_id])
    @client.is_active = false

    if @client.save
      redirect_to client_path(@client), notice: 'El cliente fue desactivado'
    else
      redirect_to client_path(@client), notice: 'No pudimos deactivar este cliente'
    end
  end

end

app/controllers/exportation_controller.rb
class ExportationController < ApplicationController

  def generate_bills
  end

  #
  # These files are generated with clients that have no payments in the current
  # month. The charge information is intended to be sent to the entity
  # that makes the charges.
  #
  def generate_charges

    respond_to do |format|
      format.csv { send_data Client.pendign_payments_csv, filename: 'archivo-de-cobros.csv' }
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    #
    # This action takes care of showing the main
    # page for the application, here, we're showing
    # the actions that the user can take, Generating reports
    # importing files and more.
    #
    def index
    end

end

app/controllers/importation_controller.rb
class ImportationController < ApplicationController

  def sales
  end
  
  # 
  # Main action to import sales files.
  #
  def import_sales_xls
    file = params[:file]
    importer = SaleImportation.new
    message = importer.import_xls(file.path)

    redirect_to sales_path, notice: message
  end

  def payments
  end
  
  #
  # Import payments file
  #
  def import_payments_xls
    file = params[:file]
    importer = PaymentImportation.new
    message = importer.import_xls(file.path)

    redirect_to payments_path, notice: message
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/exportation_helper.rb
module ExportationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/importation_helper.rb
module ImportationHelper
end

app/views/client/index.html.erb
<div class="container container-sm client-list">
    <h2 class="text-xs-center">Clientes</h2>
    <p class="text-muted text-xs-center">Listado de clientes <strong><% if params[:status] == 'active' %>activos<% else %>inactivos<% end %></strong>, ver <strong><% if params[:status] == 'active' %>inactivos<% else %>activos<% end %></strong></p>
    <br>

    <div class="client-list-actions">
        <h5>Generar reporte de clientes</h5>
        <a href="<%= "#{client_index_path('csv')}?status=active" %>" class="btn btn-success">Activos</a>
        <a href="<%= "#{client_index_path('csv')}?status=inactive" %>" class="btn btn-success">Inactivos</a>
    </div>

    <table class="table">
        <thead class="thead-default">
            <tr>
                <th>#</th>
                <th>Nombres</th>
                <th>Apellidos</th>
                <th>Número de documento</th>
                <th>Numero celular</th>
                <th>Dirección</th>
                <th>Campaña</th>
                <th>Ciudad</th>
            </tr>
      </thead>
      <tbody>
        <% if !@client_list.blank? %>
            <% for client in @client_list %>
                <tr>
                    <th scope="row"><%= client.id %></th>
                    <td><a href="<%= client_path(client) %>"><%= client.first_name %></a></td>
                    <td><%= client.last_name %></td>
                    <td><%= client.document_number %></td>
                    <td><%= client.cellphone_number %></td>
                    <td><%= client.address %></td>
                    <td><%= client.campaign %></td>
                    <td><%= client.city %></td>
                </tr>
            <% end %>
        <% else %>
            <tr>
                <td colspan="8" scope="row"><center>No encontramos clientes con los criterios que especificaste.</center></td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>

app/views/client/show.html.erb
<div class="container container-sm client-detail">
    <h1><%= @client.first_name %> <%= @client.last_name %></h1>
    <hr>

    <h6 class="text-muted">Número de documento</h6>
    <h4><%= @client.document_number %></h4>

    <h6 class="text-muted">Numero celular</h6>
    <h4><%= @client.cellphone_number %></h4>

    <h6 class="text-muted">Ciudad</h6>
    <h4><%= @client.city %></h4>

    <h6 class="text-muted">Dirección</h6>
    <h4><%= @client.address %></h4>

    <h6 class="text-muted">Campaña</h6>
    <h4><%= @client.campaign %></h4>

    <h6 class="text-muted">Estado</h6>
    <% if @client.is_active %>
        <h4>Activo</h4>
    <% else %>
        <h4>Inactivo</h4>
    <% end %>

    <% if @client.is_active %>
        <h6 class="text-muted">Desactivar usuario</h6>
        <a class="btn btn-danger" data-confirm="¿Estas seguro?" href="<%= client_deactivate_path(@client) %>">Desactivar</a>
    <% end %>

    <hr>
    <h2>Pagos</h2>
    <div class="card payment-list">
        <table class="table">
            <thead class="thead-default">
                <tr>
                    <th>#</th>
                    <th>Fecha inicial</th>
                    <th>Fecha final</th>
                    <th>Fecha de pago</th>
                </tr>
            </thead>
            <tbody>
                <% if !@client.payments.blank? %>
                    <% for payment in @client.payments %>
                        <tr>
                            <td><%= payment.id %></td>
                            <td><%= payment.start_date %></td>
                            <td><%= payment.end_date %></td>
                            <td><%= payment.payment_date %></td>
                        </tr>
                    <% end %>
                <% else %>
                    <tr>
                        <td colspan="3">Este cliente no registra pagos.</td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>

</div>

app/views/home/index.html.erb
<div class="container">

    <div class="starter-template">
        <h2>Selecciona una acción</h2>
        <p class="text-muted">Selecciona una tarea en la parte inferior</p>
        <br>
        <div class="col-md-3">
            <div class="card card-inverse card-primary">
                <div class="card-block">
                    <h3 class="card-title">Cargar Ventas</h3>
                    <p class="card-text">Cargar ventas hechas en Call Center.</p>
                    <a href="<%= sales_path %>" class="btn btn-primary">Cargar</a>
                </div>
            </div>
        </div>

        <div class="col-md-3">
            <div class="card card-inverse card-success">
                <div class="card-block">
                    <h3 class="card-title">Generar cobros</h3>
                    <p class="card-text">Generación de archivo de cobros</p>
                    <a href="<%= charges_path('csv') %>" class="btn btn-success">Ver mas</a>
                </div>
            </div>
        </div>

        <div class="col-md-3">
            <div class="card card-inverse card-warning">
                <div class="card-block">
                    <h3 class="card-title">Cargar Pagos</h3>
                    <p class="card-text">Cargar archivo de cobros exitosos desde entidad.</p>
                    <a href="<%= payments_path %>" class="btn btn-warning">Cargar</a>
                </div>
            </div>
        </div>

        <div class="col-md-3">
            <div class="card card-inverse card-danger">
                <div class="card-block">
                    <h3 class="card-title">Clientes</h3>
                    <p class="card-text">Listado de clientes activos e inactivos</p>
                    <%= link_to 'Ver clientes', "#{client_index_path}?status=active", class: 'btn btn-danger' %>
                </div>
            </div>
        </div>

    </div>

</div>

app/views/importation/payments.html.erb
<div class="container">

    <h2 class="text-xs-center">Cargar pagos</h2>
    <p class="text-muted text-xs-center">Importación de archivo generado por entidad de cobro. Carga un archivo excel (.xlsx) con las siguientes columnas:</p>
    <br>

    <div class="card">
        <table class="table">
            <thead class="thead-default">
                <tr>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Cédula</th>
                    <th>Celular</th>
                    <th>Fecha</th>
                    <th>Valor</th>
                    <th>Venta</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Camilo Andres</td>
                    <td>Trejos</td>
                    <td>1086754876</td>
                    <td>3117569933</td>
                    <td>15/10/2016</td>
                    <td>20000</td>
                    <td>9</td>
                </tr>
            </tbody>
        </table>
    </div>
    <p class="font-italic">Los nombres de las columnas del Excel deben ser exactamente como se muestran en esta tabla.</p>
    <br>

    <%= bootstrap_form_tag url: payments_path, :html => {:multipart => true} do |f| %>
            <div class="form-group">
                <label>Cargar archivo de pagos</label>
                <%= file_field_tag "file", class: 'form-control-file' %>
                <small class="form-text text-muted">Archivo .xlsx</small>
            </div>

            <div class="form-group">
                <%= f.submit 'Cargar archivo', class: 'btn btn-success' %>
            </div>
        <% end %>

</div>

app/views/importation/sales.html.erb
<div class="container">

    <h2 class="text-xs-center">Cargar ventas</h2>
    <p class="text-muted text-xs-center">Importación de archivo generado por call center. Carga un archivo excel (.xlsx) con las siguientes columnas:</p>
    <br>

    <div class="card">
        <table class="table">
            <thead class="thead-default">
                <tr>
                    <th>Nombres</th>
                    <th>Apellidos</th>
                    <th>Cédula</th>
                    <th>Celular</th>
                    <th>Campana</th>
                    <th>Direccion</th>
                    <th>Ciudad</th>
                    <th>Fecha de venta</th>
                    <th>Valor</th>
                    <th>No tarjeta</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Camilo Andres</td>
                    <td>Trejos</td>
                    <td>1086754876</td>
                    <td>3117569933</td>
                    <td>Compensar</td>
                    <td>Calle 95 # 7-40</td>
                    <td>Bogotá</td>
                    <td>24/09/2016</td>
                    <td>20000</td>
                    <td>1234</td>
                </tr>
            </tbody>
        </table>
    </div>
    <p class="font-italic">Los nombres de las columnas del Excel deben ser exactamente como se muestran en esta tabla.</p>
    <br>

    <%= bootstrap_form_tag url: sales_path, :html => {:multipart => true} do |f| %>
            <div class="form-group">
                <label>Cargar archivo de ventas</label>
                <%= file_field_tag "file", class: 'form-control-file' %>
                <small class="form-text text-muted">Archivo .xlsx</small>
            </div>

            <div class="form-group">
                <%= f.submit 'Cargar archivo', class: 'btn btn-success' %>
            </div>
        <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Andi Asistencia</title>
        <%= csrf_meta_tags %>
        <meta name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" integrity="sha384-2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <nav class="navbar navbar-fixed-top navbar-dark bg-blue">
            <div class="container">
                <a class="navbar-brand" href="/">Andi Asistencia</a>
            </div>
        </nav>

        <div class="container">
            <% flash.each do |key, value| %>
                <div class="alert alert-info">
                  <%= value %>
                </div>
            <% end %>
        </div>

        <%= yield %>
  </body>
</html>